version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: dockerzon
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5432:5432'
    volumes:
      - dockerzon-postgres:/var/lib/postgresql/data
    deploy:
      placement:
        max_replicas_per_node: 1

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - dockerzon-redis:/var/lib/redis/data
    deploy:
      placement:
        max_replicas_per_node: 1

  dockerzon:
    build:
      context: .
    volumes:
      - .:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: rails s -b 0.0.0.0
    deploy:
      placement:
        max_replicas_per_node: 1


  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env
    deploy:
      placement:
        max_replicas_per_node: 1

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.nginx
  #   links:
  #     - dockerzon
  #   ports:
  #     - '8020:8020'

volumes:
  dockerzon-postgres:
  dockerzon-redis:
